name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run:  sudo apt-get install -y libstdc++-10-dev g++-10 gcc-10 cmake libssl-dev libtbb-dev libre2-dev libyaml-cpp-dev nlohmann-json3-dev
      - name: Configure
        run: |
          cmake -S . -B cmake-build-debug -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Debug -DTORRENTTOOLS_BUILD_TESTS=ON
      - name: Build
        run: cmake --build cmake-build-debug
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: torrenttools-binaries
          path: |
            cmake-build-debug
            !cmake-build-debug/_deps
          retention-days: 1

  test:
    name: Test
    needs: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install runtime dependencies
        run: sudo apt-get install -y libstdc++-10-dev g++-10 gcc-10 libssl-dev libtbb-dev libre2-dev libyaml-cpp-dev nlohmann-json3-dev
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: torrenttools-binaries
          path: cmake-build-debug
      - name: Display structure of downloaded files
        run: ls -R
      - name: Test
        run: |
          chmod +x cmake-build-debug/tests/torrenttools-tests
          cd cmake-build-debug && ctest